name: Poll data (hourly)

on:
  workflow_call:
    inputs:
      pollers:
        required: true
        type: string

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  poll-data-hourly:
    uses: ./.github/workflows/poll-data.yml
    with:
      pollers: hourly
