name: Poll data (daily)

on:
  workflow_call:
    inputs:
      pollers:
        required: true
        type: string

on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  poll-data-daily:
    uses: ./.github/workflows/poll-data.yml
    with:
      pollers: daily
