name: Poll data

concurrency: poll-data

# Requires these repository secrets:
# TELEGRAM_TOKEN - a token for the Telegram bot API
# TELEGRAM_DEBUG_CHAT_ID - the ID of the private Telegram channel
# GITHUB_PAT - a personal access token with the repo scope

on:
  schedule:
    - cron: '*/20 * * * *' # Every 20 minutes
  workflow_dispatch:

jobs:
  poll-data:
    environment: vaterstetten-in-zahlen.de
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install
      - name: Poll data
        run: pipenv run python tools/poll.py --telegram-token=$TELEGRAM_TOKEN --telegram-debug-chat-id=$TELEGRAM_DEBUG_CHAT_ID
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_DEBUG_CHAT_ID: ${{ secrets.TELEGRAM_DEBUG_CHAT_ID }}
        continue-on-error: true
        timeout-minutes: 10
      - name: Commit
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: automatic data update
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: GitHub Actions <actions@github.com>
      - if: steps.auto-commit-action.outputs.changes_detected == 'true'
        name: Trigger Deploy workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
