name: URL checker

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check URLs
        uses: urlstechie/urlchecker-action@0.0.34
